### PR TITLE
Highscore refactor

### PR DESCRIPTION
**Pull request by Verzijl**
Should fix an error some people have. 
And fixed so the correct score is added.

<bug

### CODE REVIEW

**Comment by jimhommes** [comment]
My main remarks are fixed, :shipit:

**Comment by LilideBree** [comment]
I'm still getting 2 errors. In monster test testDie and testDieNull, are still errors. Both give nullpointerexcpetions.

**Comment by toinehartman** [comment]
All tests pass on mine. Did you try `mvn clean test`?

**Comment by LilideBree** [comment]
Maven works fine, is JUnit test coverage.

**Comment by toinehartman** [comment]
Maven just runs JUnit tests. So it's your IDE that fails.

**Comment by toinehartman** [comment]
Only remark by me is that the highscore is a String instead of an int. This is quite strange, it is a number right? If that is fixed, :shipit: .

**Comment by JPluim** [comment]
:shipit:

**Pull request merged**
