### PR TITLE
Multi live

### PR DESCRIPTION
**Pull request by Verzijl**
The player now has multiple lives. And when the player still has lives left and collides with a monster a lives is subtracted and the player is immortal for 3 seconds (turns red as well) and is transported to the starting position of that level.

### CODE REVIEW

**Comment by Verzijl** [comment]
Fixes #168 and #169. 

<feature

**Comment by jimhommes** [comment]
I think there should be a delay between dieing and respawning. Right now if you die on the spawn location you just turn immortal and then you lose a life.

<feature

**Comment by jimhommes** [comment]
Overall comment: A lot of responsibilities are now part of LevelController while they should be part of Player. 

Right now for example, Player is checking the amount of lives in LevelController. This should be the other way around. 

<organisation

**Comment by LilideBree** [comment]
All the power ups are gone.

<bug

**Comment by LilideBree** [comment]
Your power up is not connected to the health bar, you need to add a life when a heart has been picked up.

<bug

**Comment by LilideBree** [comment]
That or the observer isn't working properly. Try playing the game for a bit, and you'll see.

<bug

**Comment by LilideBree** [comment]
Test coverage has decreased by 4% for the src/main

<testing

**Comment by LilideBree** [comment]
For a new level, it almost seems like the counter goes back to 5 lives, but doesn't change until you die. So when I finish level 1 with 2 lives, and then die in level 2, I'm back to 4 lives.

<bug

**Comment by LilideBree** [comment]
:shipit: 

<feature

**Pull request merged**
