### PR TITLE
Fixed score and levels from reset on next level.

### PR DESCRIPTION
**Pull request by Verzijl**
<bug

### CODE REVIEW

**Comment by LilideBree** [comment]
Have you written tests for this?

**Comment by Verzijl** [comment]
Nope, I did not. Apparently they are not there. Will look at that.

**Comment by Verzijl** [comment]
This branch can be merged. It is just to fix the bug. Tests wil be put in a different branch.

**Comment by Verzijl** [comment]
Fixed #197 and #200

**Pull request merged**
