### PR TITLE
Added different songs for different stages of the game.

### PR DESCRIPTION
**Pull request by JPluim**
Added music for:
- Final level with boss
- Game over
- Game won
  To have all music in the same style also changed the originally used theme song to the NES. 

I do am getting a warning from my SDK: "This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h."

Does any of you also got this error (cause I suspect it's locally on my Mac). 
<feature

### CODE REVIEW

**Comment by LilideBree** [comment]
This is a gap in the music between the music loops, it is a bit odd.

**Comment by LilideBree** [comment]
You are going to get a problem with Jeffrey's branch, because he added another level as the final boss level. So the music at the moment is in the wrong place.

**Comment by JPluim** [comment]
Thats not going to be problem, since the boss-song is played at last map in the array maps. So if a map is added, the last map is still taken as the 'boss-level'.

**Comment by LilideBree** [comment]
Cool, then you are right, that isn't a problem.

**Comment by LilideBree** [comment]
:shipit:

**Pull request merged**
