### PR TITLE
Improve ta comments

### PR DESCRIPTION
**Pull request by jimhommes**
Improved comments in the issue. Travis is failing because of the FXML tests, see Matthijs his fix.

<organisation

### CODE REVIEW

**Comment by toinehartman** [comment]
You remod the location from Player and Bubble, but the comment was as follows: "I still do not understand why SpriteBase is responsible for the locations of the objects like Bubble and Player." This means that location should be in Player and Bubble, and should be removed from SpriteBase.

**Comment by jimhommes** [comment]
We had this discussion with the TA, and he said that he would not mind anymore. The main remark was if it was a pure MVC pattern or not. But, he said that because we had the discussion it wouldn't influence the grade that badly.

<layout

**Comment by LilideBree** [comment]
Can you please merge development into this?

**Comment by LilideBree** [comment]
:shipit: 
Can someone else double check, seeing that this is a big merge?

**Comment by JPluim** [comment]
:shipit:

**Pull request merged**
